import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  agreementTitle: {
    position: 'absolute',
    top: 60,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'Pretendard-Regular',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    marginTop: 105,
    textAlign: 'left',
    alignSelf: 'flex-start',
    fontFamily: 'Pretendard-Bold',
  },
  highlight: {
    color: '#389348',
    fontFamily: 'Pretendard-Bold',
  },
  allCheckboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1.2,
    borderRadius: 10,
    width: '100%',
    justifyContent: 'center',
    height: 58,
    marginTop: 10,
  },
  allCheckboxText: {
    fontSize: 19,
    color: '#555',
    marginLeft: 8,
    fontWeight: '15',
    fontFamily: 'Pretendard-Bold',
  },
  noticeTitle: {
    fontSize: 20,
    color: '#333',
    fontWeight: 'bold',
    marginBottom: 5,
    alignSelf: 'flex-start',
    fontFamily: 'Pretendard-Bold',
    textAlign: 'left',
  },
  notice: {
    fontSize: 14,
    color: '#888',
    marginTop: 0,
    marginBottom: 30,
    textAlign: 'left',
    fontFamily: 'Pretendard-Regular',
    alignSelf: 'flex-start',
  },
  checkboxContainer: {
    width: '100%',
  },
  checkboxItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  checkboxIconContainer: {
    width: 20,
    height: 20,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 2,
  },
  checked: {
    backgroundColor: '#389348',
  },
  checkboxText: {
    fontSize: 18,
    color: '#333',
    marginLeft: 10,
    fontFamily: 'Pretendard-Regular',
    flexWrap: 'wrap',
    maxWidth: '72%',
  },
  submitButton: {
    marginTop: 26,
    paddingVertical: 20,
    paddingHorizontal: 80,
    borderRadius: 10,
    width: '100%',
  },
  submitButtonActive: {
    backgroundColor: '#389348',
  },
  submitButtonInactive: {
    backgroundColor: '#E0E0E0',
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Pretendard-Bold',
    textAlign: 'center',
  },
  submitButtonTextActive: {
    color: '#fff',
  },
  submitButtonTextInactive: {
    color: '#A0A0A0',
  },
});
