import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f0f0',
  },
  scrollView: {
    flexGrow: 1,
    padding: 20,
  },
  section: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  amountUsedToday: {
    color: '#55555E',
    textAlign: 'left',
    fontFamily: 'Pretendard-Medium',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 18,
    marginBottom: 5,
  },
  amountComparison: {
    color: '#666',
    fontFamily: 'Pretendard-Medium',
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 20,
  },
  bold: {
    fontFamily: 'Pretendard-Bold',
    fontWeight: 'bold',
  },
  red: {
    color: 'red',
    fontFamily: 'Pretendard-Bold',
    fontWeight: 'bold',
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 17,
    padding: 20,
    marginBottom: 20,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  cardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardText: {
    flex: 1,
    marginBottom: 5,
  },
  title: {
    fontSize: 17,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#389348',
    lineHeight: 19,
  },
  level: {
    fontSize: 9,
    fontFamily: 'Pretendard-Medium',
    fontWeight: '500',
    color: '#55555E',
    lineHeight: 19,
  },
  levelValue: {
    fontSize: 13,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#389348',
    lineHeight: 19,
  },
  progressBarBackground: {
    height: 9,
    backgroundColor: '#E6E6E6',
    borderRadius: 10,
    marginTop: 4,
    width: '100%',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#389348',
    borderRadius: 10,
    width: '70%',
  },
  subtitle: {
    fontSize: 13,
    fontFamily: 'Pretendard-Medium',
    fontWeight: '500',
    color: '#55555E',
    marginTop: 13,
    lineHeight: 19,
  },
  value: {
    fontSize: 15,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#389348',
    lineHeight: 19,
  },
  characterImage: {
    width: 150,
    height: 150,
    marginLeft: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#333',
    marginBottom: 10,
  },
  tasks: {
    flex: 1,
  },
});
