import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f0f0',
  },
  scrollView: {
    flexGrow: 1,
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  userName: {
    color: '#000',
    textAlign: 'center',
    fontFamily: 'Pretendard-Bold',
    fontSize: 27.077,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 35.041,
  },
  userSuffix: {
    color: '#55555E',
    fontFamily: 'Pretendard-Medium',
    fontSize: 27.077,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 35.041,
  },
  iconsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconWithText: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  iconText: {
    marginLeft: 4,
    fontSize: 15.287,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#5D5D5D',
    textAlign: 'center',
    lineHeight: 19.783,
  },
  notificationBadge: {
    position: 'absolute',
    right: -6,
    top: -4,
    backgroundColor: 'green',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationText: {
    color: '#FFF',
    fontSize: 12,
    fontFamily: 'Pretendard-Bold',
    fontWeight: 'bold',
  },
  amountUsedToday: {
    color: '#55555E',
    textAlign: 'left',
    fontFamily: 'Pretendard-Medium',
    fontSize: 14.124,
    fontStyle: 'normal',
    fontWeight: '500',
    lineHeight: 18.278,
    marginTop: 12,
  },
  amountComparison: {
    fontSize: 14,
    fontFamily: 'Pretendard-Medium',
    marginTop: 5,
    color: '#666',
    marginBottom: 26,
    textAlign: 'left',
  },
  bold: {
    fontFamily: 'Pretendard-Bold',
    fontWeight: 'bold',
  },
  red: {
    fontFamily: 'Pretendard-Bold',
    color: 'red',
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 17.196,
    padding: 20,
    marginBottom: 20,
    marginTop: 8,
  },
  cardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardText: {
    flex: 1,
    marginBottom: 5,
  },
  title: {
    fontSize: 17.196,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#389348',
    lineHeight: 19.489,
  },
  level: {
    fontSize: 9.171,
    fontFamily: 'Pretendard-Medium',
    fontWeight: '500',
    color: '#55555E',
    lineHeight: 19.489,
  },
  levelValue: {
    fontSize: 12.611,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#389348',
    lineHeight: 19.489,
  },
  progressBarBackground: {
    height: 9,
    backgroundColor: '#E6E6E6',
    borderRadius: 10,
    marginTop: 4,
    width: '100%',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#389348',
    borderRadius: 10,
    width: '70%',
  },
  subtitle: {
    fontSize: 12.793,
    fontFamily: 'Pretendard-Medium',
    fontWeight: '500',
    color: '#55555E',
    marginTop: 13,
    lineHeight: 19.489,
  },
  challengeCount: {
    fontSize: 13,
    fontFamily: 'Pretendard-Bold',
    fontWeight: 'bold',
    color: '#389348',
    marginTop: 2,
  },
  value: {
    fontSize: 15.374,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#389348',
    lineHeight: 19.489,
  },
  characterImage: {
    width: 150,
    height: 150,
    marginLeft: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#333',
    marginTop: 20,
    marginBottom: 10,
  },
  tasks: {
    flex: 1,
  },
  task: {
    backgroundColor: '#FFF',
    borderRadius: 17.196,
    padding: 20,
    marginBottom: 10,
  },
  taskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  taskTitle: {
    fontSize: 12,
    fontFamily: 'Pretendard-Medium',
    fontWeight: '500',
    color: '#333',
    lineHeight: 19.489,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
    backgroundColor: '#E6E6E6',
  },
  safe: {
    borderRadius: 3.439,
    backgroundColor: '#81C966',
  },
  warning: {
    borderRadius: 3.439,
    backgroundColor: '#F7941D',
  },
  danger: {
    borderRadius: 3.439,
    backgroundColor: '#FF4C4C',
  },
  statusBadgeText: {
    fontSize: 12,
    fontFamily: 'Pretendard-Bold',
    fontWeight: 'bold',
    color: '#FFF',
  },
  taskContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  amountUsed: {
    fontSize: 13,
    fontFamily: 'Pretendard-Medium',
    fontWeight: '500',
    color: '#333',
    lineHeight: 19.489,
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  safeIconWithText: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  safeIconText: {
    color: '#FFF',
    textAlign: 'center',
    WebkitTextStrokeWidth: 1.3685320615768433,
    WebkitTextStrokeColor: '#81C966',
    fontFamily: 'Pretendard',
    fontSize: 13.389,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 17.328, 
  },

  progressBar: {
    height: 9,
    backgroundColor: '#E6E6E6',
    borderRadius: 10,
    marginTop: 10,
    position: 'relative',
    overflow: 'hidden',
  },
  progress: {
    height: '100%',
    borderRadius: 10,
  },
  goalLine: {
    position: 'absolute',
    height: '100%',
    width: 2,
    backgroundColor: '#333',
  },
  goalAmountContainer: {
    position: 'absolute',
    right: 0,
    top: -20,
  },
  goalAmount: {
    fontSize: 13,
    fontFamily: 'Pretendard-Bold',
    fontWeight: '700',
    color: '#333',
  },
});
